### ISSUE TITLE
R codes are missing

### ISSUE THREAD

**Issue by dave007007007** [Aviator10/Predictive-Model-for-choosing-correct-shipping-mode-Supply-chain-and-Logistic-Analytics#1]
R codes are missing

**Comment by Aviator10** [comment]
Not sure why you are not able to see it.  I can see. Anyways check the link

[(https://github.com/Aviator10/Predictive-Model-for-choosing-correct-shipping-mode-Supply-chain-and-Logistic-Analytics/blob/master/CPG1_SCLAGroupAssignment.R)]
